### ISSUE TITLE
Discuss Additional Features to Add

### ISSUE THREAD

**Issue by KingZiad** [KingZiad/SOEN-341#42]
Let us finally discuss what we would like to add. This should be easily evaluated once the core features are done

**Comment by MarwaKhalid** [comment]
Please check the four additional features posted, if those are enough and we dont need more then close this issue

**Comment by MarwaKhalid** [comment]
Making a public profile page is one, and now we need one more additional feature idea

**Comment by MarwaKhalid** [comment]
Closing this issue
