### ISSUE TITLE
Sub-User Story: A User can Sort the Questions by Date/Time

### ISSUE THREAD

**Issue by MarwaKhalid** [KingZiad/SOEN-341#51]
Sub-User Story:
---------
As a user, I want to be able to sort the questions by date or time so that I can view the most recently posted questions.

Deadline: 
-------------
Dec 2

Points:
----------
Risk Level: Low
Priority Level: High
Story Points: 1

Acceptance Criteria:
----------------------
- [ ]  GIVEN the user attempts to view the questions, WHEN the sort by date button is clicked THEN the questions are sorted by date/time

| Step | Test Steps | Notes |
| ------|   ----------| --- |
| 1 |  Go to Website | Website is active |
| 2 | User can sign in  | Username and Password match | 
| 3 | Access the questions | Redirects to Question Page | 
| 4 | User can sort the questions | The questions are sorted by date/time |

**Comment by K-eng-a** [comment]
Added a when statement to the acceptance criteria.
