### ISSUE TITLE
Sub-User Story: A User can see the number of people who viewed the Question

### ISSUE THREAD

**Issue by MarwaKhalid** [KingZiad/SOEN-341#52]
Sub-User Story:
---------
As a user, I want to be able to see the number of views for a question so that I am aware of the quality of answers.

Deadline:
---------
Dec 2

Points:
---------
Risk Level: Low
Priority Level: High
Story Points: 3

Acceptance Criteria:
----------------------
- [ ]  GIVEN the user attempts to view the question WHEN the question is selected and the user is redirected THEN the page must display total view count.

| Step | Test Steps | Notes |
| ------|   ----------| --- |
| 1 |  Go to Website | Website is active |
| 2 | User can sign in  | Username and Password match | 
| 3 | Access the questions | Redirects to Question Page | 
| 4 | User can view one question at a time | Redirects to the page of that specific question where the view count is displayed and updated constantly |

**Comment by K-eng-a** [comment]
Edited the User Story and Acceptance Criteria
