### ISSUE TITLE
Sub-User Story: A User can see the Date the Question was Posted

### ISSUE THREAD

**Issue by MarwaKhalid** [KingZiad/SOEN-341#53]
Sub-User Story:
--------
As a user, I want to be able to see what date the question was posted so that I am aware whether it's regarding a newer version of an IDE or an older version.

Deadline:
----------
Dec 2

Points:
-----------
Risk Level: Low
Priority Level: High
Story Points: 3

Acceptance Criteria:
----------------------
- [ ]  GIVEN the user attempts to view a question WHEN a question is selected and the user is redirected THEN the date of posting must be displayed.

| Step | Test Steps | Notes |
| ------|   ----------| --- |
| 1 |  Go to Website | Website is active |
| 2 | User can sign in  | Username and Password match | 
| 3 | Access the questions | Redirects to Question Page | 
| 4 | User can view a specific chosen question | Redirects to Question page where the date of posting is listed |

**Comment by K-eng-a** [comment]
Edited the sub-user story
